### ISSUE TITLE
After install the sidebar starts up too small

### ISSUE THREAD

**Issue by pwr22** [olsh/Google-Tasks-Sidebar#1]
By default simple mode is not selected so the sidebar is far too small for the richer layout

**Comment by pwr22** [comment]
@olsh do you use the simple or complex view? I find the complex one too cluttered and so never use it

**Comment by olsh** [comment]
I use the simple view. I agree that complex one is very cumbersome for the sidebar.
We could change the default options [here](https://github.com/olsh/Google-Tasks-Sidebar/blob/master/src/package.json#L16).

**Comment by pwr22** [comment]
Is it still worth supporting the complex view. Just trying it out there are two issues

1. It isn't actually a sidebar
2. On a 1080p monitor it needs to be resized to the maximum possible width to be usable at all. There doesn't seem to be any way to do this programmatically

**Comment by pwr22** [comment]
Apologies if the Russian translation isn't right, I did my best with Google Translate

**Comment by olsh** [comment]
> Apologies if the Russian translation isn't right, I did my best with Google Translate

It's right :) . Good job.
